server:
  port: 8080
spring:
  application:
    name: reggie
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1998
  redis:
    host: 192.168.1.117
    port: 6379
    password: zs19981219
    database: 0
mybatis-plus:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: E:\Desktop\JAVA笔记\reggie\photo\

